apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-sample-serving-only
spec:
  version: "v1.0.0"
  image: "openfunctiondev/e2e-v1beta1-knative:latest"
  port: 8080 # default to 8080
  serving:
    runtime: knative
    template:
      containers:
        - name: function
          imagePullPolicy: Always
